### ISSUE TITLE
DataBase

### ISSUE THREAD

**Issue by Romanstha** [niteeshchaudhary/TruPen#1]
Where is database file?

**Comment by niteeshchaudhary** [comment]
Here We did not create database file explicitly. 
If you see code in IITdh_portal.php file you will get to know we are making creating database there if do not exists and create some tables insert 1 or two records into it.
So it is like as u will through website and enter information the required tables will automatically generate if they do not exist.
If you want a database file explicitly then u may go through files(php files) where the dabases creation queries, table creation queries and insertion queries are there copy them and put them into file.
Here we did this so that anybody can clone, start xampp(password of mysql ="" or change it ) and he is ready to now he doesn't have to do extra steps to run it

**Comment by niteeshchaudhary** [comment]
if you have no further queries shall i close the issue?

**Comment by Romanstha** [comment]
It would be helpful if you provide me database explicitly.

**Comment by niteeshchaudhary** [comment]
Added as database.sql see if it works for u

**Comment by Romanstha** [comment]
Hello author, i got many errors while importing database. There are
home.html and index.html file so whenever i tried to access the webpage
it'll open index.html file. But at first php will access index.php file, Am
i right sir ?
Can you please fox these errors sir ?
It would be very helpful for me.

Looking forward for your reply.
Lots of love sir.
Thank you.
